# Generated by Django 5.0.3 on 2024-04-16 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_items_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menus',
            name='link',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
