# Generated by Django 5.0.3 on 2024-04-17 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_menus_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menus',
            name='link',
            field=models.CharField(blank=True, default='#', max_length=255),
        ),
    ]
