# Generated by Django 5.0.3 on 2024-04-27 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='content2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='type',
            field=models.CharField(choices=[('Page', 'Page'), ('Section', 'Section'), ('Widget', 'Widget')], default='Page', max_length=255),
        ),
    ]
