# Generated by Django 5.0.3 on 2024-05-13 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hud', '0003_posorder_posorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='posorder',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
