# Generated by Django 5.0.3 on 2024-05-13 08:10

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hud', '0004_posorder_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='posorderitem',
            name='subtotal',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('price'), '*', models.F('quantity')), output_field=models.DecimalField(decimal_places=2, max_digits=6)),
        ),
    ]
