# Generated by Django 5.0.3 on 2024-05-14 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hud', '0007_posorderitem_subtotal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posorderitem',
            old_name='subtotal',
            new_name='subtotal2',
        ),
    ]
