# Generated by Django 5.0.3 on 2024-05-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hud', '0008_rename_subtotal_posorderitem_subtotal2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posorderitem',
            name='subtotal2',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=3, default=3, max_digits=11),
        ),
    ]
