# Generated by Django 5.0.3 on 2024-05-15 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hud', '0009_remove_posorderitem_subtotal2_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcode',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='barcode', to='hud.product'),
        ),
        migrations.AlterField(
            model_name='barcode',
            name='value',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
