# Generated by Django 5.0.3 on 2024-05-15 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hud', '0010_alter_barcode_product_alter_barcode_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posorderitem',
            name='price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
    ]
