# Generated by Django 5.0.3 on 2024-05-16 08:13

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hud', '0011_alter_posorderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='posorderitem',
            name='subtotal',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('price'), '*', models.F('quantity')), output_field=models.DecimalField(decimal_places=3, max_digits=15)),
        ),
    ]
