# Generated by Django 5.0.3 on 2024-05-16 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hud', '0012_posorderitem_subtotal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('rate', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('is_fixed', models.BooleanField(default=False)),
                ('is_tax_on_total', models.BooleanField(default=False)),
                ('is_enabled', models.BooleanField(default=False)),
                ('amount', models.FloatField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productTaxes', to='hud.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productTaxes', to=settings.AUTH_USER_MODEL)),
                ('tax', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productTaxes', to='hud.tax')),
            ],
        ),
        migrations.AddConstraint(
            model_name='producttax',
            constraint=models.UniqueConstraint(fields=('product', 'tax'), name='unique_product_taxes'),
        ),
    ]
