# Generated by Django 5.0.3 on 2024-05-16 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hud', '0013_tax_producttax_producttax_unique_product_taxes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posorderitem',
            name='subtotal',
        ),
    ]
