# Generated by Django 5.0.3 on 2024-05-16 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hud', '0014_remove_posorderitem_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='posorderitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
    ]
