# Generated by Django 5.0.3 on 2024-05-17 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hud', '0016_customer_customerdiscount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posorder',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='hud.customer'),
        ),
    ]
