# Generated by Django 5.0.3 on 2024-05-17 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hud', '0017_posorder_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posorder',
            name='customer',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='hud.customer'),
        ),
    ]
