# Generated by Django 5.0.3 on 2024-05-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hud', '0018_alter_posorder_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posorderitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
