# Generated by Django 5.0.3 on 2024-05-20 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hud', '0020_posorder_item_subtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posorderitem',
            name='discount_type',
            field=models.FloatField(choices=[(0, 'IQD'), (1, '%')], default=0),
        ),
    ]
