# Generated by Django 5.0.3 on 2024-05-20 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hud', '0021_alter_posorderitem_discount_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posorderitem',
            name='discount_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'IQD'), (1, '%')], default=0),
        ),
    ]
