# Generated by Django 5.0.3 on 2024-05-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hud', '0022_alter_posorderitem_discount_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='posorderitem',
            name='discount_sign',
            field=models.GeneratedField(db_persist=False, expression=models.Case(models.When(discount_type=1, then=models.Value('%')), models.When(discount_type=0, then=models.Value('$')), default=models.Value(''), output_field=models.CharField(max_length=20)), output_field=models.CharField(max_length=20)),
        ),
        migrations.AlterField(
            model_name='posorderitem',
            name='discount_type',
            field=models.FloatField(default=0),
        ),
    ]
