# Generated by Django 5.0.3 on 2024-05-20 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hud', '0025_posorderitem_item_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posorder',
            name='item_subtotal',
        ),
    ]
