# Generated by Django 5.0.3 on 2024-05-21 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hud', '0027_posorder_item_subtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posorder',
            name='discount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='posorder',
            name='discount_type',
            field=models.FloatField(default=0),
        ),
    ]
