# Generated by Django 5.0.3 on 2024-05-21 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hud', '0030_posorder_subtotal_after_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posorder',
            name='item_subtotal',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
    ]
