# Generated by Django 5.0.3 on 2024-05-21 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hud', '0031_alter_posorder_item_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='posorder',
            name='total_tax',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
    ]
