# Generated by Django 5.0.3 on 2024-05-21 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hud', '0032_posorder_total_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posorder',
            name='subtotal_after_discount',
        ),
        migrations.AlterField(
            model_name='posorder',
            name='total_tax',
            field=models.FloatField(default=0),
        ),
    ]
