# Generated by Django 5.0.3 on 2024-05-21 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hud', '0033_remove_posorder_subtotal_after_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posorder',
            name='total',
        ),
        migrations.AddField(
            model_name='posorder',
            name='fixed_taxes',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='posorder',
            name='subtotal_after_discount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='posorder',
            name='total_tax_rate',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='posorder',
            name='total_tax',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
    ]
