# Generated by Django 5.0.3 on 2024-05-21 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hud', '0035_posorder_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posorderitem',
            name='subtotal',
        ),
    ]
