# Generated by Django 5.0.3 on 2024-05-21 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hud', '0036_remove_posorderitem_subtotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posorder',
            name='total',
        ),
    ]
