# Generated by Django 5.0.3 on 2024-05-21 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hud', '0037_remove_posorder_total'),
    ]

    operations = [
    
    ]
