# Generated by Django 5.0.3 on 2024-05-21 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hud', '0038_rename_total_tax_posorder_total_tax_payer'),
    ]

    operations = [
        migrations.AddField(
            model_name='posorder',
            name='total_tax_payer',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
    ]
