# Generated by Django 5.0.3 on 2024-05-21 07:40

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hud', '0042_remove_posorder_subtotal_after_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='posorder',
            name='subtotal_after_discount',
            field=models.GeneratedField(db_persist=False, expression=django.db.models.expressions.CombinedExpression(models.F('item_subtotal'), '-', models.F('discounted_amount')), output_field=models.DecimalField(decimal_places=3, default=0, max_digits=15)),
        ),
    ]
