# Generated by Django 5.0.3 on 2024-05-21 07:58

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hud', '0047_remove_posorder_total_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='posorder',
            name='total_tax',
            field=models.GeneratedField(db_persist=False, expression=django.db.models.expressions.CombinedExpression(models.F('fixed_taxes'), '+', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('subtotal_after_discount'), '*', models.F('total_tax_rate')), '/', models.Value(100))), output_field=models.DecimalField(decimal_places=3, default=0, max_digits=15)),
        ),
    ]
