# Generated by Django 5.0.3 on 2024-05-21 07:59

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hud', '0048_posorder_total_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='posorder',
            name='total',
            field=models.GeneratedField(db_persist=False, expression=django.db.models.expressions.CombinedExpression(models.F('subtotal_after_discount'), '+', models.F('total_tax')), output_field=models.DecimalField(decimal_places=3, default=0, max_digits=15)),
        ),
    ]
