# Generated by Django 5.0.3 on 2024-03-31 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configurations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('input_type', models.CharField(choices=[('', 'Select InputType'), ('text', 'text'), ('textarea', 'textarea'), ('file', 'file'), ('checkbox', 'checkbox'), ('radio', 'radio'), ('button', 'button'), ('select', 'select')], default='', max_length=255)),
                ('editable', models.BooleanField(default=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('params', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'configuration',
                'verbose_name_plural': 'configurations',
            },
        ),
    ]
