# Generated by Django 5.0.3 on 2024-03-31 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_about_user_facebook_url_user_linkedin_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.CharField(blank=True, help_text='Pattern = dd-mm-yyyy', max_length=255, null=True),
        ),
    ]
