# Generated by Django 5.0.3 on 2024-04-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blogs_content2'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
