# Generated by Django 5.0.3 on 2024-04-29 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_blogs_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='note',
        ),
        migrations.AlterField(
            model_name='blogs',
            name='content2',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
