# Generated by Django 5.0.3 on 2024-04-29 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_remove_blogs_note_alter_blogs_content2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='content2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
